name: torch
channels:
  - defaults
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - pytorch
  - numpy
  - torchmetrics
  - pandas
  - torchvision
  - scikit-learn
  - tensorboard
  - h5py
  - yacs
  - pytorch-cuda=11.7
  - torchaudio
  - trimesh
