exp:
  name: 'base'
  seed: 1
  epochs: 250
  batch_size: 32
  test_batch_size: 16
  log_interval: 1000

model:
  extractor: 'ours'
  dropout: 0.5
  loss: 'bce_loss'
  k: 20

data:
  name: 'breaking_bad'
  subset: 'artifact' 
  num_points: 2048
  # Proportion of the complete dataset
  prop_dt: 1.0
  # Proportion of test from the complete datset
  prop_test: 0.7
  # Proportion of validation from the training datset
  prop_val: 0.7
  # Proportion between postive and negative samples
  prop_pn: 0.6

opt:
  scheduler: 'CosineAnnealingLR'
  name: 'SGD'
  lr: 0.1
  lr_min: 0.001
  gamma: 0.9
  weight_decay: 0.0001