exp:
  name: 'vn_ours_2048'
  seed: 1
  epochs: 400
  batch_size: 32
  test_batch_size: 16
  log_interval: 1000

model:
  extractor: 'vn_ours'
  dropout: 0.5
  loss: 'cal_loss'
  k: 20

data:
  name: 'modelnet40'
  subset: '' 
  num_points: 2048

opt:
  scheduler: 'CosineAnnealingLR'
  name: 'Adam'
  lr: 0.001
  lr_min: 0.00001
  gamma: 0.9
  weight_decay: 0.0001
